Re-enable RTTI (needed in order to subclass Source, etc.)
Commit c98344f in snappy 1.1.9 disabled RTTI, which means the
snappy library no longer exports typeinfo for snappy::Source,
snappy::Sink, ..., so users of the library can't subclass these
classes anymore.

Here's a trivial reproducer:

  #include <snappy-sinksource.h>
  class MySource : snappy::Source {
  public:
    size_t Available() const override { return 0; }
    const char *Peek(size_t *len) override { return NULL; }
    void Skip(size_t n) override {}
  };
  int main(int argc, char **argv) {
    MySource m;
    return 0;
  }

Try `g++ -o snappy-test ./snappy-test.cc -lsnappy` with the above
and the linker will fail with "undefined reference to `typeinfo
for snappy::Source'" if RTTI was disabled in the snappy build.