Fix compilation in clang, unused variable
Compilign with clang in OSX gives this:

    snappy.cc:96:18: error: unused variable 'kLiteralOffset' [-Werror,-Wunused-const-variable]

A recent commit replaced the uses of kLiteralOffset,  but it is
still mentioned in comments, so to keep those making some sense,
this commit comments out the variable too.